// `esm` emitter: a generated ES module that exports the bundled records, so a
// consumer can `import` baked data directly with no fetch and no build step.
//
// Options:
//   file?          output filename (default 'baked.mjs')
//   export?        named export identifier (default 'BAKED')
//   defaultExport? also emit `export default` (default true)
//   header?        custom banner comment
//   provenance?    include the per-job provenance table (default true)
//   shape?         `buckets` (default) or `records`
//   merge?         merge this run over the previous module (default false)
//
// With `merge: true` the previous module is imported (cache-busted) and its
// configured export — or its default export — is merged with this run's
// records before the module is rewritten, so a partial run keeps previously
// published data. The module is validated as exact JSON and written atomically.
//
// Consumer-side shapes are config, not hardcoded: a bucket-shaped aggregate
// plus provenance is one valid config, a flat record list is another.

import path from 'node:path';
import { bundleRecords } from '../bundle.mjs';
import {
  assertJsonSafe,
  mergeRecordLists,
  mergeRecordsIntoBundle,
  readModuleArtifact,
  validateForPublish,
  writeFileAtomic,
} from '../publish.mjs';

export const name = 'esm';

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

export async function emit(records, ctx) {
  const { outDir, options = {}, provenance = {}, version = 1, generator = 'mothbake' } = ctx;
  const exportName = options.export ?? 'BAKED';
  if (!IDENTIFIER.test(exportName)) {
    throw new Error(`esm: export "${exportName}" is not a valid JavaScript identifier`);
  }
  const file = options.file ?? 'baked.mjs';
  const target = path.join(outDir, file);
  const label = `esm emitter (${file})`;
  const includeProvenance = options.provenance !== false;
  const previous = options.merge ? await readModuleArtifact(target, exportName, label) : null;

  let data;
  if (options.shape === 'records') {
    data = options.merge ? mergeRecordLists(previous, records) : records;
    if (!Array.isArray(data)) throw new Error(`${label}: shape "records" must produce an array`);
    assertJsonSafe(data, label);
  } else {
    const table = includeProvenance ? provenance : {};
    data = options.merge
      ? mergeRecordsIntoBundle(previous, records, { version, generator, provenance: table, keepProvenance: includeProvenance })
      : bundleRecords(records, { version, generator, provenance: table });
    validateForPublish(data, { expectedProvenance: includeProvenance ? Object.keys(provenance) : [], label });
  }

  const header = options.header ?? `// GENERATED by ${generator} — do not edit by hand.\n// Regenerate with: mothbake run`;
  const lines = [header, '', `export const ${exportName} = ${JSON.stringify(data, null, 2)};`];
  if (options.defaultExport !== false) lines.push('', `export default ${exportName};`);
  lines.push('');
  writeFileAtomic(target, lines.join('\n'));
  return [target];
}
