// `esm` emitter: a generated ES module that exports the bundled records, so a
// consumer can `import` baked data directly with no fetch and no build step.
//
// Options:
//   file?          output filename (default 'baked.mjs')
//   export?        named export identifier (default 'BAKED')
//   defaultExport? also emit `export default` (default true)
//   header?        custom banner comment
//   provenance?    include the per-job provenance table (default true)
//   shape?         `buckets` (default) or `records`
//
// Consumer-side shapes are config, not hardcoded: a bucket-shaped aggregate
// plus provenance is one valid config, a flat record list is another.

import fs from 'node:fs';
import path from 'node:path';
import { bundleRecords } from '../bundle.mjs';

export const name = 'esm';

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

export function emit(records, ctx) {
  const { outDir, options = {}, provenance = {}, version = 1, generator = 'mothbake' } = ctx;
  const exportName = options.export ?? 'BAKED';
  if (!IDENTIFIER.test(exportName)) {
    throw new Error(`esm: export "${exportName}" is not a valid JavaScript identifier`);
  }
  const target = path.join(outDir, options.file ?? 'baked.mjs');
  const data =
    options.shape === 'records'
      ? records
      : bundleRecords(records, { version, generator, provenance: options.provenance === false ? {} : provenance });
  const header = options.header ?? `// GENERATED by ${generator} — do not edit by hand.\n// Regenerate with: mothbake run`;
  const lines = [header, '', `export const ${exportName} = ${JSON.stringify(data, null, 2)};`];
  if (options.defaultExport !== false) lines.push('', `export default ${exportName};`);
  lines.push('');
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, lines.join('\n'));
  return [target];
}
