// GENERATED by mothbake — do not edit by hand.
// Regenerate with: mothbake run

export const BAKED = {
  "version": 1,
  "generator": "mothbake",
  "provenance": {
    "tile-job": {
      "engine": "blur-v1",
      "jobId": "job-fixture-tile",
      "mode": "emu",
      "name": "rock",
      "credits": 1
    },
    "sky-job": {
      "engine": "blur-v1",
      "jobId": null,
      "mode": "emu",
      "name": "nebula",
      "credits": 1
    },
    "normals-job": {
      "engine": "blur-core-v1",
      "jobId": null,
      "mode": "emu",
      "name": "rock",
      "credits": 1
    },
    "rift-job": {
      "engine": "blur-core-v1",
      "jobId": null,
      "mode": "emu",
      "name": "rift",
      "credits": 1
    }
  },
  "textures": {
    "rock": {
      "width": 8,
      "height": 8,
      "format": "rgba8",
      "data": "AAAA/wMDA/8BAQD/AgIC/wMDA/8EBAP/AwMD/wAAAP8CAgH/DAsJ/xEQDf8TEQ//FhQS/xQSEP8TEQ//AwIC/wQEA/8QDwz/FhQR/xYUEv8aFxX/FBIQ/xUTEf8FBAT/AwMD/xMRD/8XFRL/FRMQ/xoXFP8XFRL/EQ8N/wQEA/8EBAP/GRcT/xsYFf8aGBX/IyAc/x8cGP8UExD/BQUE/wMDA/8VExH/EhEO/xQSEP8aGBX/FhUS/xoYFf8EBAP/AgIC/xAODP8RDw3/EA8N/xgWE/8WFBH/GBYT/wMDAv8BAAD/BAQD/wEBAf8DAwL/BQQE/wYFBP8FBAT/AQEA/w==",
      "resample": "bilinear",
      "periodicProcessing": false,
      "seamDiagnostics": {
        "mean": 0.002546,
        "max": 0.007843,
        "exact": false
      },
      "qualityWarnings": [
        "Opposite boundaries differ; inspect the 3x3 tiled preview before approval."
      ]
    }
  },
  "sky": {
    "nebula": {
      "width": 8,
      "height": 4,
      "format": "rgba8",
      "data": "AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8=",
      "sourceProjection": "equirectangular",
      "projectionConversion": "none",
      "equirect": true
    }
  },
  "normals": {
    "rock": {
      "width": 4,
      "height": 4,
      "format": "rgba8",
      "data": "gH///4CA//9/f///f3///4CA//9/gP//f3///4CA//+AgP//f3///3+A//+AgP//gH///39///9/gP//gH///w=="
    }
  },
  "effects": {
    "rift": {
      "fps": 10,
      "frames": [
        {
          "width": 4,
          "height": 4,
          "format": "rgba8",
          "data": "Ch4o/woeKP8KHij/Ch4o/woeKP8KHij/Ch4o/woeKP8KHij/Ch4o/woeKP8KHij/Ch4o/woeKP8KHij/Ch4o/w=="
        }
      ]
    }
  }
};

export default BAKED;
