// GENERATED by mothbake — do not edit by hand.
// Regenerate with: mothbake run

export const BAKED = {
  "version": 1,
  "generator": "mothbake",
  "provenance": {
    "tile-job": {
      "engine": "blur-v1",
      "jobId": "job-fixture-tile",
      "mode": "emu",
      "name": "rock",
      "credits": 1
    },
    "sky-job": {
      "engine": "blur-v1",
      "jobId": null,
      "mode": "emu",
      "name": "nebula",
      "credits": 1
    },
    "normals-job": {
      "engine": "blur-core-v1",
      "jobId": null,
      "mode": "emu",
      "name": "rock",
      "credits": 1
    },
    "rift-job": {
      "engine": "blur-core-v1",
      "jobId": null,
      "mode": "emu",
      "name": "rift",
      "credits": 1
    }
  },
  "textures": {
    "rock": {
      "width": 8,
      "height": 8,
      "format": "rgba8",
      "data": "AAAA/wEBAP8AAAD/AAAA/wAAAP8BAQH/AQEA/wEBAf8BAAD/AQEB/wEBAf8BAQH/AQEA/wICAf8BAQH/AQEB/wAAAP8BAQD/AQEB/wEBAf8BAQH/AgIB/wEBAf8BAQH/AQEA/wEBAf8CAQH/AgIB/wEBAf8CAgL/AQEB/wEBAf8BAAD/AgEB/wEBAf8CAgH/AgIB/wMDAv8BAQH/AAAA/wEBAf8DAgL/AgIC/wIBAf8CAgL/AgIC/wICAv8CAgL/AQAA/wEBAf8BAQH/AQEB/wAAAP8BAQH/AQEB/wEBAf8AAAD/AQAA/wEBAP8BAQH/AQEA/wICAv8BAQH/AQEB/w=="
    }
  },
  "sky": {
    "nebula": {
      "width": 8,
      "height": 4,
      "format": "rgba8",
      "data": "AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8=",
      "equirect": true
    }
  },
  "normals": {
    "rock": {
      "width": 4,
      "height": 4,
      "format": "rgba8",
      "data": "gH///4CA//9/f///f3///4CA//9/gP//f3///4CA//+AgP//f3///3+A//+AgP//gH///39///9/gP//gH///w=="
    }
  },
  "effects": {
    "rift": {
      "fps": 10,
      "frames": [
        {
          "width": 4,
          "height": 4,
          "format": "rgba8",
          "data": "Ch4o/woeKP8KHij/Ch4o/woeKP8KHij/Ch4o/woeKP8KHij/Ch4o/woeKP8KHij/Ch4o/woeKP8KHij/Ch4o/w=="
        }
      ]
    }
  }
};

export default BAKED;
